version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


  app:
    build: .
    restart: always
    ports:
      - 8080
    environment:
      - VIRTUAL_HOST=petclinic.local


  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    volumes:
      - "./dbdata/:/var/lib/mysql"

  ubuntu:
    image: ubuntu
